import type { LLM } from "./ai";

/**
 * Branded analytics reports (Phase 5). Aggregation and HTML rendering are pure
 * so they're unit-tested without a DB or browser. The rendered HTML is
 * white-labeled from the client's branding config and is print-ready — a PDF is
 * produced by rendering this HTML (e.g. headless Chromium) in production.
 */

export interface Snapshot {
  date: Date;
  followers: number | null;
  impressions: number | null;
  engagementRate: number | null;
}

export interface BrandingConfig {
  logoUrl?: string;
  primaryColor?: string;
  accentColor?: string;
  companyName?: string;
}

export interface ReportModel {
  from: Date;
  to: Date;
  followersStart: number;
  followersEnd: number;
  followerGrowth: number;
  totalImpressions: number;
  avgEngagementRate: number;
  points: number;
}

export function buildReportModel(
  snapshots: Snapshot[],
  range: { from: Date; to: Date },
): ReportModel {
  const sorted = [...snapshots].sort(
    (a, b) => a.date.getTime() - b.date.getTime(),
  );
  const followers = sorted
    .map((s) => s.followers)
    .filter((v): v is number => v != null);
  const followersStart = followers[0] ?? 0;
  const followersEnd = followers[followers.length - 1] ?? followersStart;

  const totalImpressions = sorted.reduce(
    (sum, s) => sum + (s.impressions ?? 0),
    0,
  );
  const rates = sorted
    .map((s) => s.engagementRate)
    .filter((v): v is number => v != null);
  const avgEngagementRate =
    rates.length > 0 ? rates.reduce((a, b) => a + b, 0) / rates.length : 0;

  return {
    from: range.from,
    to: range.to,
    followersStart,
    followersEnd,
    followerGrowth: followersEnd - followersStart,
    totalImpressions,
    avgEngagementRate,
    points: sorted.length,
  };
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const fmt = (n: number) => n.toLocaleString("en-US");
const fmtDate = (d: Date) => d.toISOString().slice(0, 10);

export function renderReportHtml(
  model: ReportModel,
  branding: BrandingConfig,
  aiSummary?: string,
): string {
  const primary = branding.primaryColor ?? "#4f8cff";
  const accent = branding.accentColor ?? "#7c5cff";
  const company = escapeHtml(branding.companyName ?? "Your Brand");
  const logo = branding.logoUrl
    ? `<img src="${escapeHtml(branding.logoUrl)}" alt="${company}" style="height:40px" />`
    : `<strong style="font-size:20px">${company}</strong>`;
  const growthSign = model.followerGrowth >= 0 ? "+" : "";

  const summaryBlock = aiSummary
    ? `<section class="summary"><h2>Summary</h2><p>${escapeHtml(aiSummary)}</p></section>`
    : "";

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8" />
<title>${company} — Performance Report</title>
<style>
  :root { --primary:${primary}; --accent:${accent}; }
  body { font-family: ui-sans-serif, system-ui, sans-serif; color:#1a1f2b; margin:0; padding:40px; }
  header { display:flex; justify-content:space-between; align-items:center; border-bottom:3px solid var(--primary); padding-bottom:16px; }
  h1 { font-size:22px; margin:24px 0 4px; }
  .period { color:#6b7280; margin:0 0 24px; }
  .grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; }
  .card { border:1px solid #e5e7eb; border-radius:12px; padding:18px; }
  .card .label { color:#6b7280; font-size:13px; }
  .card .value { font-size:26px; font-weight:700; color:var(--primary); margin-top:6px; }
  .summary { margin-top:28px; padding:18px; background:#f6f8fc; border-left:4px solid var(--accent); border-radius:8px; }
  footer { margin-top:40px; color:#9aa4b2; font-size:12px; }
</style></head>
<body>
  <header>${logo}<span style="color:var(--accent);font-weight:600">Performance Report</span></header>
  <h1>${company}</h1>
  <p class="period">${fmtDate(model.from)} – ${fmtDate(model.to)} · ${model.points} data points</p>
  <div class="grid">
    <div class="card"><div class="label">Follower growth</div><div class="value">${growthSign}${fmt(model.followerGrowth)}</div></div>
    <div class="card"><div class="label">Total impressions</div><div class="value">${fmt(model.totalImpressions)}</div></div>
    <div class="card"><div class="label">Avg engagement</div><div class="value">${(model.avgEngagementRate * 100).toFixed(1)}%</div></div>
  </div>
  ${summaryBlock}
  <footer>Generated by SocialOps · ${company} confidential</footer>
</body></html>`;
}

const REPORT_SYSTEM =
  "You write a concise 2-3 sentence executive summary of a social media " +
  "performance report for an agency's client. Be factual, reference the metrics " +
  "given, and note the trend. No preamble, no markdown.";

/** Optional AI narrative for the report (Sonnet). Uses only the given metrics. */
export async function summarizeReport(
  llm: LLM,
  model: ReportModel,
): Promise<string> {
  const text = await llm.complete({
    system: REPORT_SYSTEM,
    prompt:
      `Metrics for ${fmtDate(model.from)}–${fmtDate(model.to)}:\n` +
      `- Follower growth: ${model.followerGrowth}\n` +
      `- Total impressions: ${model.totalImpressions}\n` +
      `- Average engagement rate: ${(model.avgEngagementRate * 100).toFixed(1)}%\n\n` +
      `Write the summary:`,
    maxTokens: 200,
  });
  return text.trim();
}
